export default {
  NEW_WORD: "NEW_WORD",
  HISTORY: "HISTORY",
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  LOADING_NEW_WORD: "LOADING_NEW_WORD",
  REVEAL_HINT: "REVEAL_HINT",
  RESET_MATCH: "RESET_MATCH",
  SKIP: "SKIP",
  RESET_GAME: "RESET_GAME",
};
